#include "memory.h"

char flash_get_page_num(uint16_t addr){
	return addr <= FLASH_CODE_END_ADDRESS ? FLASH_CODE_FIRST_PAGE_NUM + ((addr - FLASH_CODE_START_ADDRESS) / FLASH_CODE_PAGE_SIZE):
		(addr >= FLASH_NV_EXT_START_ADDRESS) && (addr <= FLASH_NV_EXT_END_ADDRESS) ?
			FLASH_NV_EXT_FIRST_PAGE_NUM + ((addr - FLASH_NV_EXT_START_ADDRESS) / FLASH_NV_EXT_PAGE_SIZE):
		addr >= FLASH_NV_STD_START_ADDRESS ?
			FLASH_NV_STD_FIRST_PAGE_NUM + ((addr - FLASH_NV_STD_START_ADDRESS) / FLASH_NV_STD_PAGE_SIZE): 
		-1;
}
